version: '3.8'

services:
  frontend:
    image: bloglist-frontend
    build:
      context: ./bloglist-frontend/
      dockerfile: localhost-prod.Dockerfile
    volumes:
      - ./bloglist-frontend/:/usr/src/app
    ports:
      - 3000:80
    container_name: bloglist-frontend
  backend:
    image: bloglist-backend
    build:
      context: ./bloglist-backend/
      dockerfile: Dockerfile
    volumes:
      - ./bloglist-backend/:/usr/src/app
    ports:
      - 3001:3001
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASS}@mongo:27017/bloglist_prod
      - SECRET=${JWT_SECRET}
    container_name: bloglist-backend

  mongo:
    image: mongo:4.4.6
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root_db
    volumes: 
      - ./bloglist-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./bloglist-backend/mongo_data:/data/db
    container_name: bloglist-db
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:81
    container_name: bloglist-reverse-proxy
    depends_on:
      - frontend
      - backend
volumes:
  mongo_data:
    