version: '3.8'

services:
  frontend:
    image: bloglist-frontend-dev
    build:
      context: ./bloglist-frontend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist-frontend/:/usr/src/app
    ports:
      - 3000:3000
    container_name: bloglist-frontend-dev
  backend:
    image: bloglist-backend-dev
    build:
      context: ./bloglist-backend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist-backend/:/usr/src/app
    ports:
      - 3001:3001
    environment:
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/bloglist_db
      - SECRET="I Like Turtles"
    container_name: bloglist-backend-dev

  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: bloglist_db
    volumes: 
      - ./bloglist-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./bloglist-backend/mongo_data:/data/db
    container_name: bloglist-db
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend
volumes:
  mongo_data:
    