name: CI

on:
  push:
    branches:
      - main
    paths:
      - bloglist-frontend/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      working-directory: bloglist-frontend
      env:
        REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
        COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
      if: |
        github.event_name == 'push'
        && !contains(env.COMMIT_MESSAGES, '#skip')
      run: |
        npm install
        npm run-script build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: ./bloglist-frontend/build